version: '3.2'

services:
  pepparkaka_lerenius_se:
    container_name: "pepparkaka.lerenius.se"
    image: "victorgamelounge/pepparkaka.lerenius.se:production"
    volumes:
      - ./docker/nginx/production:/etc/nginx/conf.d:rw
      - ./app:/usr/share/nginx/html/
      - ./app/assets:/var/www/html/assets
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    environment:
      - VIRTUAL_HOST=pepparkaka.lerenius.se,localhost,192.168.1.26
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
    networks:
      - nginx-proxy
    links:
      - "php_pepparkaka_lerenius_se"
    depends_on:
      - "php_pepparkaka_lerenius_se"
    command: [nginx-debug, '-g', 'daemon off;']
    expose:
      - "80"

  php_pepparkaka_lerenius_se:
    container_name: "php_pepparkaka.lerenius.se"
    image: "victorgamelounge/php_pepparkaka.lerenius.se:production"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app:/var/www/html/
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
